import express from 'express';
import cors from 'cors';
import {Readable} from 'node:stream';
import {spawn} from 'node:child_process';
import {mkdtemp,rm,stat,readdir,readFile} from 'node:fs/promises';
import {tmpdir} from 'node:os';
import path from 'node:path';
import {fileURLToPath} from 'node:url';

const app=express();
const PORT=Number(process.env.PORT||10000);
const ROOT=path.dirname(fileURLToPath(import.meta.url));
const PUBLIC=path.join(ROOT,'public');
const MAX_BYTES=200*1024*1024;
const MAX_DURATION=15*60;
app.use(cors());
app.use(express.json({limit:'32kb'}));
app.use(express.static(PUBLIC,{index:false}));

function parseUrl(value){try{const u=new URL(value),h=u.hostname.toLowerCase().replace(/^www\./,'');if(u.protocol!=='https:')return null;if(h==='tiktok.com'||h.endsWith('.tiktok.com'))return{site:'tiktok'};if(h==='instagram.com'||h.endsWith('.instagram.com'))return{site:'instagram'};if(h==='t.me'||h==='telegram.me'||h==='telegram.dog')return{site:'telegram'};return null}catch{return null}}
function child(args,{cmd='yt-dlp',timeout=45000}={}){return new Promise((resolve,reject)=>{const p=spawn(cmd,args,{stdio:['ignore','pipe','pipe']});let out='',err='',done=false;const timer=setTimeout(()=>{if(done)return;done=true;try{p.kill('SIGTERM')}catch{};reject(new Error(`${cmd} timeout`))},timeout);p.stdout.on('data',d=>out+=d);p.stderr.on('data',d=>err+=d);p.on('error',e=>{if(done)return;done=true;clearTimeout(timer);reject(e)});p.on('close',c=>{if(done)return;done=true;clearTimeout(timer);c===0?resolve(out):reject(new Error(err.trim().split('\n').filter(Boolean).slice(-1)[0]||`${cmd} failed`))})})}
const ytdlp=(args,o={})=>child(args,{...o,cmd:'yt-dlp'});
function safeName(s){return(s||'drop-media').replace(/[^a-z0-9._-]+/gi,'_').slice(0,80)||'drop-media'}
function safeInfo(info,source,provider){const url=info.url||null;return{ok:true,title:info.title||'Media',thumbnail:info.thumbnail||null,type:info._type||'video',filesize:info.filesize||info.filesize_approx||null,width:info.width||null,height:info.height||null,ext:info.ext||'mp4',url,items:url?[{url,title:info.title||'Media',thumbnail:info.thumbnail||null,size:info.filesize||info.filesize_approx||null,format:info.ext||'mp4',resolution:info.width&&info.height?`${info.width}×${info.height}`:''}]:[],sourceUrl:source,provider}}
function isTikTokShort(source){try{const h=new URL(source).hostname.toLowerCase();return h==='vm.tiktok.com'||h==='vt.tiktok.com'||h==='m.tiktok.com'||h==='tiktok.com'}catch{return false}}
async function resolveTikTokUrl(source){try{const r=await fetch(source,{redirect:'follow',headers:{'User-Agent':'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 Chrome/131.0 Safari/537.36','Accept':'text/html,application/xhtml+xml'},signal:AbortSignal.timeout(12000)});return r.url||source}catch{return source}}
function tikwmNormalize(json,source,provider){if(!json||json.code!==0||!json.data)throw new Error(json?.msg||'TikWM returned no data');const d=json.data;const url=d.hdplay||d.play||d.wmplay||d.sdplay;if(!url)throw new Error('TikWM returned no video URL');if(Number(d.duration)>MAX_DURATION)throw new Error('video is too long');return{ok:true,title:d.title||'TikTok video',thumbnail:d.cover||d.origin_cover||null,type:'video',filesize:Number(d.size||d.hd_size||0)||null,width:Number(d.width)||null,height:Number(d.height)||null,ext:'mp4',url,items:[{url,title:d.title||'TikTok video',thumbnail:d.cover||d.origin_cover||null,size:Number(d.size||d.hd_size||0)||null,format:'MP4',resolution:d.width&&d.height?`${d.width}×${d.height}`:''}],sourceUrl:source,provider}}
async function tikwmGet(source){const u=`https://www.tikwm.com/api/?url=${encodeURIComponent(source)}&hd=1`;const r=await fetch(u,{headers:{'User-Agent':'Mozilla/5.0','Accept':'application/json,text/plain,*/*','Referer':'https://www.tikwm.com/'},signal:AbortSignal.timeout(25000)});const t=await r.text();if(!r.ok)throw new Error(`TikWM GET HTTP ${r.status}`);let j;try{j=JSON.parse(t)}catch{throw new Error('TikWM GET invalid JSON')}return tikwmNormalize(j,source,'tikwm-get')}
async function tikwmPost(source){const body=new URLSearchParams({url:source,hd:'1'});const r=await fetch('https://www.tikwm.com/api/',{method:'POST',headers:{'Content-Type':'application/x-www-form-urlencoded;charset=UTF-8','Accept':'application/json,text/plain,*/*','Referer':'https://www.tikwm.com/','User-Agent':'Mozilla/5.0'},body,signal:AbortSignal.timeout(25000)});const t=await r.text();if(!r.ok)throw new Error(`TikWM POST HTTP ${r.status}`);let j;try{j=JSON.parse(t)}catch{throw new Error('TikWM POST invalid JSON')}return tikwmNormalize(j,source,'tikwm-post')}
async function tdown(source){const u=`https://tdownv4.sl-bjs.workers.dev/?down=${encodeURIComponent(source)}`;const r=await fetch(u,{headers:{'User-Agent':'Mozilla/5.0','Accept':'application/json,text/plain,*/*'},redirect:'follow',signal:AbortSignal.timeout(25000)});const t=await r.text();if(!r.ok)throw new Error(`TDown HTTP ${r.status}`);let j;try{j=JSON.parse(t)}catch{throw new Error('TDown invalid JSON')}const url=j.download_url||j.downloadUrl||j.video_url||j.url||j.data?.download_url||j.data?.url;if(!url)throw new Error(j.error||j.message||'TDown returned no video URL');return{ok:true,title:j.title||j.author?.nickname||'TikTok video',thumbnail:j.thumbnail||j.cover||null,type:'video',filesize:null,width:null,height:null,ext:'mp4',url,items:[{url,title:j.title||'TikTok video',thumbnail:j.thumbnail||j.cover||null,size:null,format:'MP4',resolution:''}],sourceUrl:source,provider:'tdown'}}
async function clipx(source){const u=`https://clipx.zamdev.workers.dev/?url=${encodeURIComponent(source)}`;const r=await fetch(u,{headers:{'User-Agent':'Mozilla/5.0','Accept':'application/json,text/plain,*/*'},signal:AbortSignal.timeout(25000)});const t=await r.text();if(!r.ok)throw new Error(`ClipX HTTP ${r.status}`);let j;try{j=JSON.parse(t)}catch{throw new Error('ClipX invalid JSON')}const d=j.data||j;const url=d.download_url||d.downloadUrl||d.video_url||d.url||d.media_url;if(!url)throw new Error(j.error||j.message||'ClipX returned no video URL');return{ok:true,title:d.title||'TikTok video',thumbnail:d.thumbnail||d.cover||null,type:'video',filesize:null,width:null,height:null,ext:'mp4',url,items:[{url,title:d.title||'TikTok video',thumbnail:d.thumbnail||d.cover||null,size:null,format:'MP4',resolution:''}],sourceUrl:source,provider:'clipx'}}
async function ytTikTok(source){const resolved=await resolveTikTokUrl(source);const info=JSON.parse(await ytdlp(['--dump-single-json','--no-playlist','--skip-download','--no-warnings','--no-check-certificates','--socket-timeout','15',resolved],{timeout:35000}));if(info.duration>MAX_DURATION)throw new Error('video is too long');return safeInfo(info,source,'yt-dlp')}
async function firstSuccess(tasks){return new Promise((resolve,reject)=>{let left=tasks.length;let settled=false;const errors=[];for(const [name,fn] of tasks){Promise.resolve().then(fn).then(v=>{if(!settled&&v?.url){settled=true;resolve(v)}else{left--;if(!left&&!settled)reject(new Error(errors.join(' | ')||'no media URL'))}}).catch(e=>{errors.push(`${name}: ${e?.message||e}`);left--;if(!left&&!settled)reject(new Error(errors.join(' | ')))})}})}
async function tiktokInfo(source){const tasks=[['TikWM GET',()=>tikwmGet(source)],['TikWM POST',()=>tikwmPost(source)],['TDown',()=>tdown(source)],['ClipX',()=>clipx(source)],['yt-dlp',()=>ytTikTok(source)]];try{return await firstSuccess(tasks)}catch(e){console.error('[TikTok providers]',e?.message||e);throw new Error(`TikTok providers failed: ${String(e?.message||e).slice(0,1500)}`)}}
function telegramPath(source){const u=new URL(source),p=u.pathname.split('/').filter(Boolean);if(p[0]==='s')p.shift();if(p.length<2)return null;return{channel:p[0].replace(/^@/,''),id:p[1]}}
async function telegramInfo(source){const p=telegramPath(source);if(!p||!/^[A-Za-z0-9_]+$/.test(p.channel)||!/^[0-9]+$/.test(p.id))throw new Error('invalid Telegram post link');const r=await fetch(`https://t.me/${p.channel}/${p.id}?embed=1`,{headers:{'User-Agent':'Mozilla/5.0'},signal:AbortSignal.timeout(20000)});if(!r.ok)throw new Error(`Telegram HTTP ${r.status}`);const h=await r.text();const get=re=>{const m=h.match(re);return m?m[1].replace(/&amp;/g,'&').replace(/&#x2F;/g,'/'):null};const video=get(/<meta[^>]+property=["']og:video(?::url)?["'][^>]+content=["']([^"']+)/i)||get(/<meta[^>]+name=["']twitter:player:stream["'][^>]+content=["']([^"']+)/i)||get(/<video[^>]+src=["']([^"']+)/i);const image=get(/<meta[^>]+property=["']og:image["'][^>]+content=["']([^"']+)/i);if(!video&&!image)throw new Error('Telegram media unavailable');const title=get(/<meta[^>]+property=["']og:title["'][^>]+content=["']([^"']+)/i)||`Telegram ${p.channel}`;const url=video||image;return{ok:true,title,thumbnail:image||null,type:video?'video':'image',filesize:null,width:null,height:null,ext:video?'mp4':'jpg',url,items:[{url,title,thumbnail:image||null,size:null,format:video?'MP4':'JPG',resolution:''}],sourceUrl:source,provider:'telegram'}}
async function instagramInfo(source){const jobs=[['yt-dlp',async()=>{const info=JSON.parse(await ytdlp(['--dump-single-json','--no-playlist','--skip-download','--no-warnings','--no-check-certificates','--socket-timeout','15',source],{timeout:45000}));if(info.duration>MAX_DURATION)throw new Error('video is too long');return safeInfo(info,source,'yt-dlp')}],['gallery-dl',async()=>{const out=await child(['-g','-f','best',source],{cmd:'gallery-dl',timeout:45000});const url=out.trim().split(/\s+/).find(x=>/^https?:\/\//.test(x));if(!url)throw new Error('gallery-dl returned no media URL');return{ok:true,title:'Instagram media',thumbnail:null,type:'video',filesize:null,width:null,height:null,ext:'mp4',url,items:[{url,title:'Instagram media',thumbnail:null,size:null,format:'MP4',resolution:''}],sourceUrl:source,provider:'gallery-dl'}}];try{return await firstSuccess(jobs)}catch(e){console.error('[Instagram providers]',e?.message||e);throw new Error(`Instagram providers failed: ${String(e?.message||e).slice(0,1500)}`)}}
async function fetchToResponse(url,r,filename='drop-media.mp4'){const media=await fetch(url,{headers:{'User-Agent':'Mozilla/5.0','Accept':'*/*'},redirect:'follow',signal:AbortSignal.timeout(30000)});if(!media.ok||!media.body)throw new Error(`media HTTP ${media.status}`);const len=Number(media.headers.get('content-length')||0);if(len>MAX_BYTES)throw new Error('file too large');r.setHeader('Content-Type',media.headers.get('content-type')||'application/octet-stream');r.setHeader('Content-Disposition',`attachment; filename="${safeName(filename)}"`);return Readable.fromWeb(media.body).pipe(r)}
app.get('/health',(q,r)=>r.json({ok:true,service:'drop',version:'race-v2',providers:{tiktok:['tikwm-get','tikwm-post','tdown','clipx','yt-dlp'],instagram:['yt-dlp','gallery-dl'],telegram:['telegram-embed']}}));
app.post('/api/resolve',async(q,r)=>{const source=String(q.body?.url||'').trim();const parsed=parseUrl(source);if(!parsed)return r.status(400).json({error:'Поддерживаются HTTPS-ссылки TikTok, Instagram и публичных Telegram-постов.'});try{if(parsed.site==='tiktok')return r.json(await tiktokInfo(source));if(parsed.site==='instagram')return r.json(await instagramInfo(source));return r.json(await telegramInfo(source))}catch(e){console.error('[resolve]',e?.stack||e);r.status(422).json({error:'Не удалось получить публичное медиа. Проверьте ссылку и доступность публикации.',diagnostic:String(e?.message||e).slice(0,1500)})}});
app.get('/api/preview',async(q,r)=>{const source=String(q.query.url||'').trim();const parsed=parseUrl(source);if(!parsed)return r.status(400).send('Invalid URL');try{const info=parsed.site==='tiktok'?await tiktokInfo(source):parsed.site==='instagram'?await instagramInfo(source):await telegramInfo(source);return r.redirect(info.url)}catch(e){r.status(422).send(String(e?.message||e))}});
app.get('/api/download',async(q,r)=>{const source=String(q.query.url||'').trim();const parsed=parseUrl(source);if(!parsed)return r.status(400).send('Invalid URL');try{const info=parsed.site==='tiktok'?await tiktokInfo(source):parsed.site==='instagram'?await instagramInfo(source):await telegramInfo(source);await fetchToResponse(info.url,r,`${info.title||'drop-media'}.${info.ext||'mp4'}`)}catch(e){console.error('[download]',e?.stack||e);if(!r.headersSent)r.status(422).send('Download unavailable')}});
app.get('/',async(q,r)=>{try{const html=await readFile(path.join(PUBLIC,'index.html'),'utf8');const fix=`<link rel="stylesheet" href="/mobile-fix.css?v=4"><script>document.addEventListener('click',function(e){const f=e.target.closest('.file-btn');if(f){const u=document.querySelector('#url')?.value?.trim();if(u){e.preventDefault();location.href='/api/download?url='+encodeURIComponent(u)}}const w=e.target.closest('.watch-btn');if(w){const u=document.querySelector('#url')?.value?.trim();if(u){e.preventDefault();window.open('/api/preview?url='+encodeURIComponent(u),'_blank')}}});</script>`;r.type('html').send(html.replace('</head>',fix+'</head>'))}catch{r.status(500).send('Application unavailable')}});
app.listen(PORT,'0.0.0.0',()=>console.log(`Drop listening on ${PORT}`));